version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task_postgres
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: trello_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d trello_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ${IMAGE_NAME:-tuusuario/task-manager}-backend:latest  
    container_name: task_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 4000
      DATABASE_URL: "postgresql://appuser:changeme@postgres:5432/trello_dev?schema=public"
      JWT_SECRET: "12345678999999"
      REFRESH_JWT_SECRET: "alejandrorichardluis"
      NODE_ENV: production
    ports:
      - "4000:4000"
    

  frontend:
    image: ${IMAGE_NAME:-alejandro231011/task-manager}-frontend:latest  # ‚Üê CAMBIO: usa imagen de Docker Hub
    container_name: task_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"  

volumes:
  pgdata:
  